---
apiVersion: v1
kind: pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd-pod
      image : httpd: 2.4.58-bookworm
      ports:
        - name: httpd-pod
          containerport: 80
          protocol: TCP