---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - image: httpd:2.4.58-bookworm
      ports:
        - name: httpd-pod
          containerport: 80
          protocol: TCP