---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd  
      image: httpd:2.4.58-bookwor
      ports:
        - name: httpd-pod
          containerport: 80
          protocol: TCP