---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
  labels: purpose-rs demo
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: tomcat-rs
      release: latest
  template:
    metadata:
      name: tomcat-rs
      labels:
        app: tomcat-rs
        release: latest
    spec:
      containers:
        - command:
            - printenv
          image: tomcat:latest
          name: tomcat
          ports:
            - containerPort: 8080
              name: tpod
              protocol: TCP




        
    




