---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
  labels:
    purpose: rs-demo
spec:
  replicas: 3
  minReadySeconds: 0
  selector:
    matchLabels:
      app: jenkins
      release: v1.1
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
        release: v1.1
    spec:
      containers:
        - image: jenkins/jenkins
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
