---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    purpose: rs-demo
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: jenkins
      release: lts-jdk17
  template:
    metadata:
      name: jenkins-rs
      labels:
        app: jenkins
        release: lts-jdk17
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk17
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
